name: Build docker-compose dev environment
on: [push, pull_request]

jobs:
  build-docker-compose:
    name: "Build docker-compose-based development environment"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: docker-compose build
        run: |
          docker-compose build --no-cache --pull
